### ISSUE TITLE
add screenshot carousel to README

### ISSUE THREAD

**Issue by dckc** [dckc/RSign#16]
_where did I see one of these?_

**Comment by JoshOrndorff** [comment]
I think the only realistic way to do this is with an animated gif. It looks like even adding css to github's readme preview isn't supported considering the hacks suggested at https://stackoverflow.com/questions/11509830/how-to-add-color-to-githubs-readme-md-file

Another option would be to have a proper project website which may become useful eventually.

**Comment by dckc** [comment]
[Making Your Code Beautiful](https://hackernoon.com/presenting-your-code-beautifully-fdbab9e6fb68) has some nifty animated svg stuff for text. Not directly relevant, but I'm bookmarking it here.

**Comment by dckc** [comment]
fixed, more or less, in 0dfeff689c0cd97d401150442c560bff47653757
